using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using FacturacionelectronicaCore.Negocio.Modelo;
using FacturacionelectronicaCore.Repositorio.Entities;
using FacturacionelectronicaCore.Repositorio.Repositorios;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace FacturacionelectronicaCore.Negocio.Contabilidad.FacturacionElectronica
{
    public class FacturacionSilog : IFacturacionElectronicaFacade
    {
        private readonly Alegra alegraOptions;
        private readonly ContactsHandler contactsHandler;
        private readonly InvoiceHandler invoiceHandler;
        private readonly ItemHandler itemHandler;
        private readonly ResolucionesHandler resolucionesHandler;
        private readonly ResolucionNumber _resolucionNumber;
        private readonly IResolucionRepositorio _resolucionRepositorio;
        private readonly IEmpleadoRepositorio _empleadoRepositorio;

        public FacturacionSilog(IOptions<Alegra> alegra, ResolucionNumber resolucionNumber, IResolucionRepositorio resolucionRepositorio, IEmpleadoRepositorio empleadoRepositorio)
        {
            alegraOptions = alegra.Value;

            _resolucionNumber = resolucionNumber;

            _resolucionRepositorio = resolucionRepositorio;
            _empleadoRepositorio = empleadoRepositorio;
        }

        public async Task ActualizarTercero(Modelo.Tercero tercero, string idFacturacion)
        {
            await contactsHandler.ActualizarCliente(idFacturacion, tercero.ConvertirAContact(), alegraOptions);
        }

        public async Task<string> GenerarFacturaElectronica(Modelo.Factura factura, Modelo.Tercero tercero, Guid estacionGuid)
        {
            try
            {
                var invoice = await GetFacturaSilog(factura, tercero, estacionGuid.ToString());
                var cedula = await _empleadoRepositorio.GetEmpleadoByName(factura.Vendedor.Trim());

                var request = new RequestContabilidad(invoice, cedula?.Trim(), alegraOptions, estacionGuid.ToString());

                Console.WriteLine(JsonConvert.SerializeObject(request));

                using (var client = new HttpClient())
                {
                    try
                    {
                        MultipartFormDataContent form = new MultipartFormDataContent();

                    var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(request));
                    var facturaBase64 = System.Convert.ToBase64String(plainTextBytes);
                    form.Add(new StringContent("generar_factura"), "function_name");
                    form.Add(new StringContent(facturaBase64), "parameter");
                    var response = await client.PostAsync(alegraOptions.Url, form);
                    response.EnsureSuccessStatusCode();

                        string responseBody = await response.Content.ReadAsStringAsync();
                        
                        // Check if the invoice was successfully generated by looking for estado:GENERADA
                        if (responseBody.Contains("\"estado\":\"GENERADA\""))
                        {
                            // Parse the response to extract invoice number and CUFE
                            dynamic jsonResponse = JsonConvert.DeserializeObject(responseBody);
                            string cufe = jsonResponse?.uuid_cufe ?? "";
                            string nroDian = "";
                            
                            try
                            {
                                var arrFacturas = jsonResponse?.datos_factura?[0]?.arr_facturas;
                                if (arrFacturas != null && arrFacturas.Count > 0)
                                {
                                    nroDian = arrFacturas[0]?.nro_dian ?? "";
                                }
                            }
                            catch { }
                            
                            return "Ok:" + nroDian + ":" + cufe + ":" + responseBody;
                        }
                        else
                        {
                            throw new AlegraException(responseBody + JsonConvert.SerializeObject(request));
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex);
                        Console.WriteLine(ex.StackTrace);
                        throw;
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                Console.WriteLine(ex.StackTrace);
                throw;
            }
        }

        public Task<FacturaSilog> GetFacturaSilog(Modelo.Factura x, Modelo.Tercero tercero, string estacionGuid)
        {
            //var numero = await _resolucionRepositorio.GetFacturaelectronicaPorPRefijo(estacionGuid.ToString());

            var nombre = "";
            var apellido = "";
            var nombreCompleto = tercero.Nombre.Trim();
            if (string.IsNullOrEmpty(tercero.Apellidos) || tercero.Apellidos.Contains("no informado"))
            {
                if (nombreCompleto.Split(' ').Count() > 1)
                {
                    nombre = nombreCompleto.Substring(0, nombreCompleto.LastIndexOf(" "));
                    apellido = nombreCompleto.Split(' ').Last();
                }
                else
                {
                    nombre = nombreCompleto;
                    apellido = "no informado";
                }
            }
            else
            {
                nombre = nombreCompleto;
                apellido = tercero.Apellidos;
            }

            var subtotal = x.SubTotal + x.Descuento;
            var total = subtotal;
            var result = new FacturaSilog()
            {
                Guid = Guid.Parse(estacionGuid),
                Consecutivo = x.Consecutivo,
                Combustible = x.Combustible,
                Cantidad = x.Cantidad,
                Precio = x.Precio,
                Total = total,
                Placa = x.Placa,
                Kilometraje = x.Kilometraje,
                Surtidor = x.Surtidor + "",
                Cara = x.Cara + "",
                Manguera = x.Manguera + "",
                FormaDePago = x.FormaDePago,
                Fecha = x.Fecha,
                Tercero = new TerceroSilog()
                {
                    Nombre = string.IsNullOrEmpty(tercero.Nombre) ? "No informado" : tercero.Nombre,
                    Direccion = string.IsNullOrEmpty(tercero.Direccion) ? "No informado" : tercero.Direccion,
                    Telefono = string.IsNullOrEmpty(tercero.Telefono) ? "No informado" : tercero.Telefono,
                    Correo = string.IsNullOrEmpty(tercero.Correo) ? "No informado" : tercero.Correo,
                    DescripcionTipoIdentificacion = string.IsNullOrEmpty(tercero.DescripcionTipoIdentificacion) ? "No especificada" : tercero.DescripcionTipoIdentificacion,
                    Identificacion = string.IsNullOrEmpty(tercero.Identificacion) ? "No informado" : tercero.Identificacion,
                    IdLocal = tercero.IdLocal
                },
                Descuento = x.Descuento,
                IdLocal = x.IdLocal,
                IdVentaLocal = x.IdVentaLocal,
                IdTerceroLocal = x.Tercero.IdLocal,
                FechaProximoMantenimiento = x.FechaProximoMantenimiento,
                SubTotal = subtotal,
                Vendedor = x.Vendedor,
                Identificacion = x.Tercero.Identificacion,
                Prefijo = x.DescripcionResolucion + x.Consecutivo,
                Cedula = tercero.Identificacion,
            };

            return Task.FromResult(result);
        }

        public Task<FacturaSilog> GetFacturaSilog(Modelo.OrdenDeDespacho orden, Modelo.Tercero tercero, string estacionGuid)
        {
            var subtotal = (decimal)orden.Total;
            var total = subtotal;
            var result = new FacturaSilog()
            {
                Guid = Guid.Parse(estacionGuid),
                Consecutivo = orden.IdVentaLocal,
                Combustible = orden.Combustible,
                Cantidad = (decimal)orden.Cantidad,
                Precio = (decimal)orden.Precio,
                Total = total,
                Placa = orden.Placa ?? "",
                Kilometraje = orden.Kilometraje?.ToString() ?? "0.00",
                Surtidor = orden.Surtidor?.ToString() ?? "1",
                Cara = orden.Cara?.ToString() ?? "1",
                Manguera = orden.Manguera?.ToString() ?? "1",
                FormaDePago = orden.FormaDePago,
                Fecha = orden.Fecha,
                Tercero = new TerceroSilog()
                {
                    Nombre = string.IsNullOrEmpty(tercero.Nombre) ? "No informado" : tercero.Nombre,
                    Direccion = string.IsNullOrEmpty(tercero.Direccion) ? "No informado" : tercero.Direccion,
                    Telefono = string.IsNullOrEmpty(tercero.Telefono) ? "No informado" : tercero.Telefono,
                    Correo = string.IsNullOrEmpty(tercero.Correo) ? "No informado" : tercero.Correo,
                    DescripcionTipoIdentificacion = string.IsNullOrEmpty(tercero.DescripcionTipoIdentificacion) ? "No especificada" : tercero.DescripcionTipoIdentificacion,
                    Identificacion = string.IsNullOrEmpty(tercero.Identificacion) ? "No informado" : tercero.Identificacion,
                    IdLocal = tercero.IdLocal
                },
                Descuento = orden.Descuento,
                IdLocal = orden.IdLocal,
                IdVentaLocal = orden.IdVentaLocal,
                IdTerceroLocal = tercero.IdLocal,
                FechaProximoMantenimiento = orden.FechaProximoMantenimiento,
                SubTotal = subtotal,
                Vendedor = orden.Vendedor ?? "",
                Identificacion = tercero.Identificacion,
                Prefijo = "FEA",
                Cedula = tercero.Identificacion,
                numeroTransaccion = orden.numeroTransaccion
            };

            return Task.FromResult(result);
        }

        public Task<FacturaSilog> GetFacturaSilog(Modelo.FacturaCanastilla factura, Modelo.Tercero tercero, string estacionGuid)
        {
            var subtotal = (decimal)factura.total;
            var total = subtotal;
            var result = new FacturaSilog()
            {
                Guid = Guid.Parse(estacionGuid),
                Consecutivo = factura.consecutivo,
                Combustible = "CANASTILLA",
                Cantidad = 1,
                Precio = (decimal)factura.total,
                Total = total,
                Placa = string.IsNullOrWhiteSpace(factura.Placa) ? "N/A" : factura.Placa.Trim(),
                Kilometraje = "0.00",
                Surtidor = "1",
                Cara = "1",
                Manguera = "1",
                FormaDePago = factura.codigoFormaPago?.Descripcion ?? "EFECTIVO",
                Fecha = factura.fecha,
                Tercero = new TerceroSilog()
                {
                    Nombre = string.IsNullOrEmpty(tercero.Nombre) ? "No informado" : tercero.Nombre,
                    Direccion = string.IsNullOrEmpty(tercero.Direccion) ? "No informado" : tercero.Direccion,
                    Telefono = string.IsNullOrEmpty(tercero.Telefono) ? "No informado" : tercero.Telefono,
                    Correo = string.IsNullOrEmpty(tercero.Correo) ? "No informado" : tercero.Correo,
                    DescripcionTipoIdentificacion = string.IsNullOrEmpty(tercero.DescripcionTipoIdentificacion) ? "No especificada" : tercero.DescripcionTipoIdentificacion,
                    Identificacion = string.IsNullOrEmpty(tercero.Identificacion) ? "No informado" : tercero.Identificacion,
                    IdLocal = tercero.IdLocal
                },
                Descuento = 0,
                IdLocal = factura.FacturasCanastillaId,
                IdVentaLocal = factura.consecutivo,
                IdTerceroLocal = tercero.IdLocal,
                FechaProximoMantenimiento = DateTime.Now.AddYears(1),
                SubTotal = (decimal)subtotal,
                Vendedor = "",
                Identificacion = tercero.Identificacion,
                Prefijo = "",
                Cedula = tercero.Identificacion,
            };

            return Task.FromResult(result);
        }

        private static string GetRegime(int responsabilidadTributaria)
        {
            switch (responsabilidadTributaria)
            {
                case 1:
                    return "AGENTE_RETENCION_IVA";
                case 2:
                    return "SIMPLE";
                case 3:
                    return "AUTORRETENEDOR";
                case 4:
                    return "AGENTE_RETENCION_IVA";
                case 5:
                    return "GRAN_CONTRIBUYENTE";
                default:
                    return "ORDINARIO";
            }
        }

        private static string GetNivelTributario(int responsabilidadTributaria)
        {
            switch (responsabilidadTributaria)
            {
                case 1:
                    return "COMUN";
                case 2:
                    return "SIMPLIFICADO";
                case 3:
                    return "NO_RESPONSABLE_DE_IVA";
                case 4:
                    return "COMUN";
                case 5:
                    return "RESPONSABLE_DE_IVA";
                default:
                    return "COMUN";
            }
        }

        private string GetTipoIdentificacion(string descripcionTipoIdentificacion)
        {
            if (descripcionTipoIdentificacion == "Nit")
            {
                return "NIT";
            }
            else
            {
                return "CC";
            }
        }
        private string GetKindOfPErson(string descripcionTipoIdentificacion)
        {
            switch (descripcionTipoIdentificacion)
            {
                case "Nit":
                    return "PERSONA_JURIDICA";
                default:
                    return "PERSONA_NATURAL";
            }
        }

        private string GetCombustible(string combustible, string estacion)
        {
            // Clean input - remove any numeric prefixes
            if (string.IsNullOrWhiteSpace(combustible))
            {
                combustible = "corriente"; // Default
            }
            
            var cleanCombustible = System.Text.RegularExpressions.Regex.Replace(combustible, @"^\d+", "").Trim().ToLower();
            
            if (cleanCombustible.Contains("corriente"))
            {
                return alegraOptions.Estaciones?.ContainsKey(estacion) == true ?
                     alegraOptions.Estaciones[estacion].Corriente ?? alegraOptions.Corriente :
                     alegraOptions.Corriente;
            }
            else if (cleanCombustible.Contains("diesel") || cleanCombustible.Contains("bioacem") || cleanCombustible.Contains("acpm"))
            {
                return alegraOptions.Estaciones?.ContainsKey(estacion) == true ?
                    alegraOptions.Estaciones[estacion].Acpm ?? alegraOptions.Acpm :
                    alegraOptions.Acpm;
            }
            else if (cleanCombustible.Contains("extra"))
            {
                return alegraOptions.Estaciones?.ContainsKey(estacion) == true ?
                   alegraOptions.Estaciones[estacion].Extra ?? alegraOptions.Extra :
                   alegraOptions.Extra;
            }
            else
            {
                return alegraOptions.Estaciones?.ContainsKey(estacion) == true ?
                    alegraOptions.Estaciones[estacion].Gas ?? alegraOptions.Gas :
                    alegraOptions.Gas;
            }
        }

        public async Task<string> GenerarFacturaElectronica(Modelo.OrdenDeDespacho orden, Modelo.Tercero tercero, Guid estacionGuid)
        {
            var formaPagoFiltro = (orden?.FormaDePago ?? string.Empty).ToLower();
            if (
                //orden.FormaDePago.ToLower().Contains("cali")||
            formaPagoFiltro.Contains("puntos")
            || formaPagoFiltro.Contains("asumidos")
            )
            {
                return null;
            }
            try
            {
                var invoice = await GetFacturaSilog(orden, tercero, estacionGuid.ToString());
                var cedula = await _empleadoRepositorio.GetEmpleadoByName(orden.Vendedor?.Trim() ?? "");

                var request = new RequestContabilidad(invoice, cedula?.Trim(), alegraOptions, estacionGuid.ToString());


                Console.WriteLine(JsonConvert.SerializeObject(request));
                var responseBody = "";
                using (var client = new HttpClient())
                {
                    try
                    {
                        // var json = JsonConvert.SerializeObject(request);
                        // var content = new StringContent(json, Encoding.UTF8, "application/json");

                        // var response = await client.PostAsync(alegraOptions.Url + "output", content);
MultipartFormDataContent form = new MultipartFormDataContent();

                    var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(request));
                    var facturaBase64 = System.Convert.ToBase64String(plainTextBytes);
                    form.Add(new StringContent("generar_factura"), "function_name");
                    form.Add(new StringContent(facturaBase64), "parameter");
                    var response = await client.PostAsync(alegraOptions.Url, form);
                        responseBody = await response.Content.ReadAsStringAsync();
                        
                        // Check if the invoice was successfully generated by looking for estado:GENERADA
                        if (responseBody.Contains("\"estado\":\"GENERADA\""))
                        {
                            // Parse the response to extract invoice number and CUFE
                            dynamic jsonResponse = JsonConvert.DeserializeObject(responseBody);
                            string cufe = jsonResponse?.uuid_cufe ?? "";
                            string nroDian = "";
                            
                            try
                            {
                                var arrFacturas = jsonResponse?.datos_factura?[0]?.arr_facturas;
                                if (arrFacturas != null && arrFacturas.Count > 0)
                                {
                                    nroDian = arrFacturas[0]?.nro_dian ?? "";
                                }
                            }
                            catch { }
                            
                            return "Ok:" + nroDian + ":" + cufe + ":" + responseBody;
                        }
                        else
                        {
                            return "Error:" + responseBody + ":" + JsonConvert.SerializeObject(request);
                        }
                    }
                    catch (Exception ex)
                    {
                        // Check if the invoice was successfully generated even if there was an exception
                        if (responseBody.Contains("\"estado\":\"GENERADA\""))
                        {
                            dynamic jsonResponse = JsonConvert.DeserializeObject(responseBody);
                            string cufe = jsonResponse?.uuid_cufe ?? "";
                            string nroDian = "";
                            
                            try
                            {
                                var arrFacturas = jsonResponse?.datos_factura?[0]?.arr_facturas;
                                if (arrFacturas != null && arrFacturas.Count > 0)
                                {
                                    nroDian = arrFacturas[0]?.nro_dian ?? "";
                                }
                            }
                            catch { }
                            
                            return "Ok:" + nroDian + ":" + cufe + ":" + responseBody;
                        }

                        Console.WriteLine(ex);
                        Console.WriteLine(ex.StackTrace);
                        return "Error:" + responseBody + ":" + JsonConvert.SerializeObject(request) + ":" + ex.Message;

                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                Console.WriteLine(ex.StackTrace);
                return "Error:" + ex.Message;
            }
        }

        public async Task<string> GenerarFacturaElectronica(List<Modelo.OrdenDeDespacho> ordenes, Modelo.Tercero tercero, IEnumerable<Item> items)
        {
            var responseBody = await invoiceHandler.CrearFatura(ordenes.ConvertirAInvoice(tercero, items), alegraOptions);
            var invoice = JsonConvert.DeserializeObject<ResponseInvoice>(responseBody);
            return invoice.numberTemplate.prefix + invoice.numberTemplate.number + ":" + invoice.id;
        }
        
        public async Task<string> GenerarFacturaElectronica(List<Modelo.Factura> facturas, Modelo.Tercero tercero, IEnumerable<Item> items)
        {
            var responseBody = await invoiceHandler.CrearFatura(facturas.ConvertirAInvoice(tercero, items), alegraOptions);
            var invoice = JsonConvert.DeserializeObject<ResponseInvoice>(responseBody);
            return invoice.numberTemplate.prefix + invoice.numberTemplate.number + ":" + invoice.id;
        }

        public async Task<int> GenerarTercero(Modelo.Tercero tercero)
        {
            return (await contactsHandler.CrearCliente(tercero.ConvertirAContact(), alegraOptions));
        }

        public async Task<ResponseInvoice> GetFacturaElectronica(string id)
        {
            return await invoiceHandler.GetFatura(id, alegraOptions);
        }

        public async Task<Item> GetItem(string name)
        {
            return await itemHandler.GetItem(name, alegraOptions);
        }

        public async Task<ResolucionElectronica> GetResolucionElectronica(string estacion)
        {
            try
            {
                var resolucion = await _resolucionRepositorio.GetFacturaelectronicaPorPRefijo(estacion);
                return new ResolucionElectronica
                {
                    invoiceText = $"Resolución Dian {alegraOptions.Prefix} {alegraOptions.ResolutionNumber} de {alegraOptions.Desde} hasta {alegraOptions.Hasta} - vigencia del {alegraOptions.DesdeFecha} al {alegraOptions.HastaFecha}",
                    prefix = resolucion.prefijo

                };
            }
            catch
            {
                return new ResolucionElectronica
                {
                    invoiceText = $"Resolución electronica - {alegraOptions.ResolutionNumber} desde 1 hasta 1000000. ",
                    prefix = alegraOptions.Prefix

                };
            }
        }

        public async Task<string> getJson(Modelo.OrdenDeDespacho orden, Guid estacion)
        {
            var invoice = await GetFacturaSilog(orden, orden.Tercero, estacion.ToString());
            var cedula = await _empleadoRepositorio.GetEmpleadoByName(orden.Vendedor?.Trim() ?? "");
            var request = new RequestContabilidad(invoice, cedula?.Trim(), alegraOptions, estacion.ToString());
            return JsonConvert.SerializeObject(request);
        }
        public async Task<IEnumerable<TerceroResponse>> GetTerceros(int start)
        {

            using (var client = new HttpClient())
            {
                client.Timeout = new TimeSpan(0, 0, 1, 0, 0);
                client.DefaultRequestHeaders.Authorization =
    new AuthenticationHeaderValue("Basic", alegraOptions.Auth);
                var path = $"{alegraOptions.Url}contacts/?start={start}";
                var response = client.GetAsync(path).Result;
                string responseBody = await response.Content.ReadAsStringAsync();
                try
                {
                    response.EnsureSuccessStatusCode();
                }
                catch (Exception)
                {
                    throw new AlegraException(responseBody);
                }

                return JsonConvert.DeserializeObject<IEnumerable<TerceroResponse>>(responseBody);
            }
        }

        public async Task<string> GenerarFacturaElectronica(Modelo.FacturaCanastilla factura, Modelo.Tercero tercero, Guid estacionGuid)
        {
            if (
                //factura.codigoFormaPago.Descripcion.ToLower().Contains("cali") || 
            factura.codigoFormaPago.Descripcion.ToLower().Contains("puntos")
            || factura.codigoFormaPago.Descripcion.ToLower().Contains("asumidos")
            )
            {
                return null;
            }
            try
            {
                var invoice = await GetFacturaSilog(factura, tercero, estacionGuid.ToString());
                var cedula = "";  // FacturaCanastilla doesn't have vendedor field

                var request = new RequestContabilidad(invoice, cedula?.Trim(), alegraOptions, estacionGuid.ToString());
                Console.WriteLine(JsonConvert.SerializeObject(request));
                var responseBody = "";
                using (var client = new HttpClient())
                {
                    try
                    {
                        MultipartFormDataContent form = new MultipartFormDataContent();

                    var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(request));
                    var facturaBase64 = System.Convert.ToBase64String(plainTextBytes);
                    form.Add(new StringContent("generar_factura"), "function_name");
                    form.Add(new StringContent(facturaBase64), "parameter");
                    var response = await client.PostAsync(alegraOptions.Url, form);
                        responseBody = await response.Content.ReadAsStringAsync();
                        
                        // Check if the invoice was successfully generated by looking for estado:GENERADA
                        if (responseBody.Contains("\"estado\":\"GENERADA\""))
                        {
                            // Parse the response to extract invoice number and CUFE
                            dynamic jsonResponse = JsonConvert.DeserializeObject(responseBody);
                            string cufe = jsonResponse?.uuid_cufe ?? "";
                            string nroDian = "";
                            
                            try
                            {
                                var arrFacturas = jsonResponse?.datos_factura?[0]?.arr_facturas;
                                if (arrFacturas != null && arrFacturas.Count > 0)
                                {
                                    nroDian = arrFacturas[0]?.nro_dian ?? "";
                                }
                            }
                            catch { }
                            
                            return "Ok:" + nroDian + ":" + cufe + ":" + responseBody;
                        }
                        else
                        {
                            return "Error:" + responseBody + ":" + JsonConvert.SerializeObject(request);
                        }
                    }
                    catch (Exception ex)
                    {
                        // Check if the invoice was successfully generated even if there was an exception
                        if (responseBody.Contains("\"estado\":\"GENERADA\""))
                        {
                            dynamic jsonResponse = JsonConvert.DeserializeObject(responseBody);
                            string cufe = jsonResponse?.uuid_cufe ?? "";
                            string nroDian = "";
                            
                            try
                            {
                                var arrFacturas = jsonResponse?.datos_factura?[0]?.arr_facturas;
                                if (arrFacturas != null && arrFacturas.Count > 0)
                                {
                                    nroDian = arrFacturas[0]?.nro_dian ?? "";
                                }
                            }
                            catch { }
                            
                            return "Ok:" + nroDian + ":" + cufe + ":" + responseBody;
                        }

                        Console.WriteLine(ex);
                        Console.WriteLine(ex.StackTrace);
                        return "Error:" + responseBody + ":" + JsonConvert.SerializeObject(request) + ":" + ex.Message;
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                Console.WriteLine(ex.StackTrace);
                return "Error:" + ex.Message;
                   
            }
        }

        public SilogRequest GetSilogRequest(Modelo.FacturaCanastilla factura, Modelo.Tercero tercero, ResolucionFacturaElectronica resolucion)
        {
            var productList = new List<ProductInformation>();

            // Agregar los productos de canastilla con IVA si aplica
            if (factura.canastillas != null)
            {
                foreach (var item in factura.canastillas)
                {
                    var product = new ProductInformation
                    {
                        ProductId = item.Canastilla?.campoextra ?? "0",
                        Quantity = (decimal)item.cantidad,
                        Discunt = 0,
                        Price = (decimal)item.precio,
                        TotalPrice = (decimal)item.total,
                        SkipAuditWarehouseValues = true
                    };
                    // Si hay IVA, agregarlo como campo adicional (puedes crear un campo IVA en ProductInformation si lo necesitas)
                    if (item.iva > 0)
                    {
                        // Si ProductInformation tiene campo IVA, descomenta la siguiente línea:
                        // product.IVA = (decimal)item.iva;
                        // Si no, puedes agregarlo como un campo extra en el diccionario o en la request final
                    }
                    productList.Add(product);
                }
            }

            // FacturaCanastilla no tiene campo vendedor, usar valores por defecto
            return new SilogRequest
            {
                UserInformation = new UserInformation
                {
                    SucursalId = string.IsNullOrWhiteSpace(resolucion.idNumeracion) || !int.TryParse(resolucion.idNumeracion.Trim(), out var sucId) ? 0 : sucId,
                    UserIdent = alegraOptions.Usuario,
                    UserPassword = alegraOptions.Token
                },
                StationInformation = new StationInformation
                {
                    Dispenser = "1",
                    Island = "1",
                    Hose = "1"
                },
                InvoiceInformation = new InvoiceInformation
                {
                    PosConsecutive = factura.consecutivo,
                    InvoiceDate = factura.fecha.ToString("yyyy-MM-dd"),
                    Details = $"Factura Canastilla: {factura.consecutivo} - Placa: {(string.IsNullOrWhiteSpace(factura.Placa) ? "N/A" : factura.Placa.Trim())}",
                    VehicleInformation = new VehicleInformation
                    {
                        Plate = string.IsNullOrWhiteSpace(factura.Placa) ? "N/A" : factura.Placa.Trim(),
                        LastMaintenanceDate = DateTime.Now.ToString("yyyy-MM-dd"),
                        NextMaintenanceDate = DateTime.Now.AddYears(1).ToString("yyyy-MM-dd"),
                        Mileage = "0.00"
                    },
                    InvoiceHolderInformation = new InvoiceHolderInformation
                    {
                        TypeId = GetTipoIdentificacionId(tercero.DescripcionTipoIdentificacion),
                        Id = tercero.Identificacion ?? "No informado",
                        Name = tercero.Nombre ?? "No informado",
                        FirstLastName = "",
                        SecondLastName = "",
                        Adress = tercero.Direccion ?? "No informado",
                        Email = tercero.Correo ?? alegraOptions.Correo,
                        PhoneNumber = GetValidPhoneNumber(tercero.Telefono)
                    },
                    ProductInformation = productList,
                    PaymentInformation = new PaymentInformation
                    {
                        PaymentFormId = GetPaymentFormId(factura.codigoFormaPago?.Descripcion,resolucion.idNumeracion),
                        PaymentMethodId = 1,
                        PaymentMeanId = 1,
                        CardId = 1,
                        TransaccionNumber = factura.consecutivo
                    }
                }
            };
        }

        public async Task<SilogRequest> GetSilogRequest(Modelo.OrdenDeDespacho orden, Modelo.Tercero tercero, ResolucionFacturaElectronica resolucion, string estacion)
        {
            var productList = new List<ProductInformation>
            {
                // Agregar el combustible como producto
                new ProductInformation
                {
                    ProductId = GetCombustible(orden.Combustible, estacion), // ID del combustible - ajustar según sea necesario
                    Quantity = (decimal)orden.Cantidad,
                    Discunt = orden.Descuento,
                    Price = (decimal)orden.Precio,
                    TotalPrice = (decimal)orden.Total,
                    SkipAuditWarehouseValues = true
                }
            };

            // Determinar si VehicleInformation debe ser null
            VehicleInformation vehicleInfo = null;
            if (!string.IsNullOrEmpty(orden.Placa) && tercero.Identificacion != "222222222222")
            {
                vehicleInfo = new VehicleInformation
                {
                    Plate = orden.Placa ?? "N/A",
                    LastMaintenanceDate = DateTime.Now.ToString("yyyy-MM-dd"),
                    NextMaintenanceDate = orden.FechaProximoMantenimiento.ToString("yyyy-MM-dd"),
                    Mileage = orden.Kilometraje?.ToString() ?? "0.00"
                };
            }

            // Buscar información del empleado
            string empleadoIdentificacion = null;
            if (!alegraOptions.AutenticaPorDefecto && !string.IsNullOrEmpty(orden.Vendedor))
            {
                empleadoIdentificacion = await _empleadoRepositorio.GetEmpleadoByName(orden.Vendedor.Trim());
            }

            var formaPagoPrincipal = GetPrimaryPaymentForm(orden.FormaDePago, orden.FormaDePago2, orden.Total1, orden.Total2);
            var detallePago = BuildPaymentDetail(orden.FormaDePago, orden.FormaDePago2, orden.Total1, orden.Total2);

            return new SilogRequest
            {
                UserInformation = new UserInformation
                {
                    SucursalId = string.IsNullOrWhiteSpace(resolucion.idNumeracion) || !int.TryParse(resolucion.idNumeracion.Trim(), out var sucId2) ? 0 : sucId2,
                    UserIdent = !string.IsNullOrEmpty(empleadoIdentificacion) ? empleadoIdentificacion : (!string.IsNullOrWhiteSpace(alegraOptions.Usuario) ? alegraOptions.Usuario : "DEFAULT"),
                    UserPassword = !string.IsNullOrEmpty(empleadoIdentificacion) ? empleadoIdentificacion : (!string.IsNullOrWhiteSpace(alegraOptions.Token) ? alegraOptions.Token : "DEFAULT")
                },
                StationInformation = new StationInformation
                {
                    Dispenser = orden.Surtidor?.ToString() ?? "1",
                    Island = "1",
                    Hose = orden.Cara?.ToString() ?? "1"
                },
                InvoiceInformation = new InvoiceInformation
                {
                    PosConsecutive = orden.IdVentaLocal,
                    InvoiceDate = orden.Fecha.ToString("yyyy-MM-dd"),
                    Details = $"Orden de Despacho: {orden.Combustible?.Trim() ?? "N/A"} - {orden.Cantidad}GL - {orden.IdVentaLocal} - Transaccion {(!string.IsNullOrWhiteSpace(orden.numeroTransaccion) ? orden.numeroTransaccion : "N/A")} - {detallePago}",
                    VehicleInformation = vehicleInfo,
                    InvoiceHolderInformation = new InvoiceHolderInformation
                    {
                        TypeId = GetTipoIdentificacionId(tercero.DescripcionTipoIdentificacion),
                        Id = tercero.Identificacion ?? "No informado",
                        Name = tercero.Nombre ?? "No informado",
                        FirstLastName = "",
                        SecondLastName = "",
                        Adress = tercero.Direccion ?? "No informado",
                        Email = tercero.Correo ?? alegraOptions.Correo,
                        PhoneNumber = GetValidPhoneNumber(tercero.Telefono)
                    },
                    ProductInformation = productList,
                    PaymentInformation = new PaymentInformation
                    {
                        PaymentFormId = GetPaymentFormId(formaPagoPrincipal, resolucion.idNumeracion),
                        PaymentMethodId = GetMethodFormId(formaPagoPrincipal, resolucion.idNumeracion),
                        PaymentMeanId = GetMeandFormId(formaPagoPrincipal, resolucion.idNumeracion),
                        CardId = 1,
                        TransaccionNumber = string.IsNullOrWhiteSpace(orden.numeroTransaccion) || !int.TryParse(orden.numeroTransaccion?.Trim(), out _) ? orden.IdVentaLocal : int.Parse(orden.numeroTransaccion.Trim())
                    }
                }
            };
        }

        private string GetPrimaryPaymentForm(string formaDePago, string formaDePago2, decimal? total1, decimal? total2)
        {
            var forma1 = string.IsNullOrWhiteSpace(formaDePago) ? "Efectivo" : formaDePago.Trim();
            var forma2 = string.IsNullOrWhiteSpace(formaDePago2) ? null : formaDePago2.Trim();

            if (string.IsNullOrWhiteSpace(forma2))
            {
                return forma1;
            }

            var valor1 = total1 ?? 0m;
            var valor2 = total2 ?? 0m;
            return valor2 > valor1 ? forma2 : forma1;
        }

        private string BuildPaymentDetail(string formaDePago, string formaDePago2, decimal? total1, decimal? total2)
        {
            var forma1 = string.IsNullOrWhiteSpace(formaDePago) ? "Efectivo" : formaDePago.Trim();
            var forma2 = string.IsNullOrWhiteSpace(formaDePago2) ? null : formaDePago2.Trim();

            if (string.IsNullOrWhiteSpace(forma2))
            {
                return $"Pago: {forma1}";
            }

            return $"Pagos: {forma1}={(total1 ?? 0m):0.##}, {forma2}={(total2 ?? 0m):0.##}";
        }

        private int GetTipoIdentificacionId(string descripcionTipoIdentificacion)
        {
            switch (descripcionTipoIdentificacion?.ToLower())
            {
                case "nit":
                    return 6;
                case "cedula":
                case "cédula ciudadanía":
                case "cc":
                    return 3;
                case "cedula extranjeria":
                case "ce":
                    return 5;
                default:
                    return 3; // Por defecto cedula
            }
        }

        private int GetPaymentFormId(string formaDePago, string sucursal)
        {
            // Handle null or empty payment form
            if (string.IsNullOrWhiteSpace(formaDePago))
            {
                return 1; // Default to cash
            }

            var cleanFormaPago = formaDePago.ToLower();
            
            if (sucursal == "603")
            {
                if (cleanFormaPago.Contains("directo"))
                {
                    return 3;
                }
                else
                {
                    return 1;
                }
            }
            if (cleanFormaPago.Contains("dito") || cleanFormaPago.Contains("cred") || cleanFormaPago.Contains("urbano")
            || cleanFormaPago.Contains("vip")
            || cleanFormaPago.Contains("doble")
            || cleanFormaPago.Contains("micro"))
            {
                return 3;
            }
            else if (cleanFormaPago.Contains("tarjeta"))
            {
                return 2;
            }
            else
            {
                return 1;
            }
        }
        private int GetMethodFormId(string formaDePago, string sucursal)
        {
            // Handle null or empty payment form
            if (string.IsNullOrWhiteSpace(formaDePago))
            {
                return 1; // Default to cash
            }

            var cleanFormaPago = formaDePago.ToLower();
            
            if (sucursal == "603")
            {
                if (cleanFormaPago.Contains("directo"))
                {
                    return 3;
                }
                else if (cleanFormaPago.Contains("efe"))
                {
                    return 1;
                }
                else if (cleanFormaPago.Contains("tarjeta"))
                {
                    return 2;
                }
                else
                {
                    return 1;
                }
            }
            if (cleanFormaPago.Contains("dito"))
            {
                return 3;
            }
            else if (cleanFormaPago.Contains("efe") || cleanFormaPago.Contains("dat"))
            {
                return 1;
            }
            else if (cleanFormaPago.Contains("cons"))
            {
                return 4;
            }
            else
            {
                return 3;
            }
        }
        private int GetMeandFormId(string formaDePago, string sucursal)
        {
            // Handle null or empty payment form
            if (string.IsNullOrWhiteSpace(formaDePago))
            {
                return 1; // Default
            }

            var cleanFormaPago = formaDePago.ToLower();
            
            if(sucursal == "603")
            {
                if (cleanFormaPago.Contains("bito"))
                {
                    return 8;
                }
                if (cleanFormaPago.Contains("tarjeta cr"))
                {
                    return 5;
                }
                else if (cleanFormaPago.Contains("directo"))
                {
                    return 3;
                }
                else
                {
                    return 1;
                }
            }
            if (cleanFormaPago.Contains("efectivo urbano"))
            {
                return 3;
            }
            if (cleanFormaPago.Contains("cred.buses.escalera"))
            {
                return 12;
            }
            if (cleanFormaPago.Contains("cred.comb.fur"))
            {
                return 14;
            }
            if (cleanFormaPago.Contains("cred.camionetas.mixed"))
            {
                return 3;
            }
            if (cleanFormaPago.Contains("cred.comb.colect.intermun"))
            {
                return 10;
            }
            if (cleanFormaPago.Contains("cred.comb.serv.especial"))
            {
                return 13;
            }
            if (cleanFormaPago.Contains("arriendo"))
            {
                return 22;
            }
            if (cleanFormaPago.Contains("cred.comb.camperos"))
            {
                return 23;
            }
            if (cleanFormaPago.Contains("vip"))
            {
                return 24;
            }
            if (cleanFormaPago.Contains("doble yo"))
            {
                return 25;
            }
            if (cleanFormaPago.Contains("microbus"))
            {
                return 26;
            }
            if (cleanFormaPago.Contains("dito"))
            {
                return 3;
            }
            else if (cleanFormaPago.Contains("efe"))
            {
                return 1;
            }
            else if (cleanFormaPago.Contains("dat") && sucursal.ToLower() == "968")
            {
                return 29;
            }
            else if (cleanFormaPago.Contains("dat") && sucursal.ToLower() == "970")
            {
                return 28;
            }
            else if (cleanFormaPago.Contains("dat"))
            {
                return 27;
            }
            else if (cleanFormaPago.Contains("cons"))
            {
                return 4;
            }
            else
            {
                return 3;
            }
        }

        private string GetValidPhoneNumber(string telefono)
        {
            // Si está vacío, es null, "No informado" o no es numérico, retornar null
            if (string.IsNullOrEmpty(telefono) ||
                telefono == "No informado" ||
                !telefono.All(char.IsDigit))
            {
                return null;
            }

            // Si es válido y numérico, aplicar padding si es necesario
            return telefono.Length < 10 ? telefono.PadLeft(10, '0') : telefono;
        }

        public Task<string> GetFacturaElectronica(string id, Guid estacionGuid)
        {
            // Implementar según necesidades específicas de Silog para obtener factura por ID y estación
            return Task.FromResult($"Factura {id} para estacion {estacionGuid}");
        }

        public Task<Item> GetItem(string name, Alegra options)
        {
            // Implementar según necesidades específicas de Silog para obtener items
            return Task.FromResult(new Item { name = name });
        }

        public Task<string> ReenviarFactura(Repositorio.Entities.OrdenDeDespacho orden, Guid estacion)
        {
            // Implementar según necesidades específicas de Silog para reenviar facturas
            return Task.FromResult("Factura reenviada");
        }

        public Task<string> getJsonCanastilla(Modelo.FacturaCanastilla facturaCanastilla, Guid estacio)
        {
            throw new NotImplementedException();
        }
    }
}