CREATE TABLE [dbo].[Facturas]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Guid] UNIQUEIDENTIFIER NOT NULL,
	[Consecutivo] INT NOT NULL,
	IdTercero INT NOT NULL,
	Combustible NVARCHAR(50),
	Cantidad Decimal(18,3),
	Precio Decimal(18,3),
	Total Decimal(18,3) NOT NULL,
	Descuento Decimal(18,3) NULL,
	IdInterno NVARCHAR(50),
	Placa NVARCHAR(50),
	Kilometraje NVARCHAR(50),
	IdResolucion Int NOT NULL,
	IdEstadoActual Int NOT NULL,
	Surtidor NVARCHAR(50),
	Cara NVARCHAR(50),
	Manguera NVARCHAR(50), 
    [Fecha] DATETIME NULL, 
	FormaDePago NVARCHAR(250) ,
	IdLocal Int  NULL,
	IdVentaLocal Int  NULL,
    [IdEstacion] INT NULL, 
    [SubTotal] DECIMAL(18, 3) NULL, 
    [FechaProximoMantenimiento] DATETIME NULL, 
    [Vendedor] NVARCHAR(50) NULL, 
    [FechaReporte] DATETIME NULL, 
    CONSTRAINT [FK_Facturas_Terceros] FOREIGN KEY ([IdTercero]) REFERENCES [Terceros]([Id]), 
    CONSTRAINT [FK_Facturas_Resolucion] FOREIGN KEY ([IdResolucion]) REFERENCES [Resolucion]([Id]), 
    CONSTRAINT [FK_Facturas_Estados] FOREIGN KEY ([IdEstadoActual]) REFERENCES [Estados]([Id])
)
