CREATE TYPE [dbo].[FacturaType] AS TABLE
(
	[Id] INT,
    [Guid] UNIQUEIDENTIFIER NOT NULL,
	[Consecutivo] INT  NULL,
	IdTercero UNIQUEIDENTIFIER NULL,
	Identificacion NVARCHAR(250),
	NombreTercero NVARCHAR(250),
	Combustible NVARCHAR(50),
	Cantidad Decimal(18,3),
	Precio Decimal(18,3),
	Total Decimal(18,3)  NULL,
	Descuento Decimal(18,3) NULL,
	IdInterno NVARCHAR(50),
	Placa NVARCHAR(50),
	Kilometraje NVARCHAR(50),
	IdResolucion UNIQUEIDENTIFIER  NULL,
	IdEstadoActual Int  NULL,
	Surtidor NVARCHAR(50),
	Cara NVARCHAR(50),
	Manguera NVARCHAR(50), 
    [Fecha] DATETIME NULL,
	Estado NVARCHAR(50),  
	IdentificacionTercero NVARCHAR(250),
	FormaDePago NVARCHAR(250) ,
	IdLocal Int  NULL,
	IdVentaLocal Int  NULL,
	IdTerceroLocal Int  NULL,
    [IdEstacion] INT NULL,
	[SubTotal] DECIMAL(18, 3) NULL, 
    [FechaProximoMantenimiento] DATETIME NULL, 
    [Vendedor] NVARCHAR(50) NULL,
    [DescripcionResolucion] varchar(50) NULL,
    [AutorizacionResolucion] varchar(50) NULL
	
)
