//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionelectronicaCore.Repositorio.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoredProcedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FacturacionelectronicaCore.Repositorio.Recursos.StoredProcedures", typeof(StoredProcedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AddFacturasImprimir].
        /// </summary>
        public static string AddFacturasImprimir {
            get {
                return ResourceManager.GetString("AddFacturasImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AddNuevaResolucion].
        /// </summary>
        public static string AddNuevaResolucion {
            get {
                return ResourceManager.GetString("AddNuevaResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AddOrdenesImprimir].
        /// </summary>
        public static string AddOrdenesImprimir {
            get {
                return ResourceManager.GetString("AddOrdenesImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AgregarFactura].
        /// </summary>
        public static string AgregarFactura {
            get {
                return ResourceManager.GetString("AgregarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AgregarFechaReporteFactura].
        /// </summary>
        public static string AgregarFechaReporteFactura {
            get {
                return ResourceManager.GetString("AgregarFechaReporteFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AgregarOModificarIsla].
        /// </summary>
        public static string AgregarIsla {
            get {
                return ResourceManager.GetString("AgregarIsla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AgregarOrdenDespacho].
        /// </summary>
        public static string AgregarOrdenDespacho {
            get {
                return ResourceManager.GetString("AgregarOrdenDespacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AgregarSurtidor].
        /// </summary>
        public static string AgregarSurtidor {
            get {
                return ResourceManager.GetString("AgregarSurtidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AnularFacturas].
        /// </summary>
        public static string AnularFacturas {
            get {
                return ResourceManager.GetString("AnularFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AnularOrdenesDeDespacho].
        /// </summary>
        public static string AnularOrdenesDeDespacho {
            get {
                return ResourceManager.GetString("AnularOrdenesDeDespacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AnularResolucion].
        /// </summary>
        public static string AnularResolucion {
            get {
                return ResourceManager.GetString("AnularResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[BorrarEstacion].
        /// </summary>
        public static string BorrarEstacion {
            get {
                return ResourceManager.GetString("BorrarEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BorrarFactura {
            get {
                return ResourceManager.GetString("BorrarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[BorrarIsla].
        /// </summary>
        public static string BorrarIsla {
            get {
                return ResourceManager.GetString("BorrarIsla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[BorrarSurtidor].
        /// </summary>
        public static string BorrarSurtidor {
            get {
                return ResourceManager.GetString("BorrarSurtidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[CrearFacturaCanastilla].
        /// </summary>
        public static string CrearFacturaCanastilla {
            get {
                return ResourceManager.GetString("CrearFacturaCanastilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[CrearFacturaDetalle].
        /// </summary>
        public static string CrearFacturaDetalle {
            get {
                return ResourceManager.GetString("CrearFacturaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[DeleteClienteByGuid].
        /// </summary>
        public static string DeleteClienteByGuid {
            get {
                return ResourceManager.GetString("DeleteClienteByGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[FacturaOrdenesDeDespacho].
        /// </summary>
        public static string FacturaOrdenesDeDespacho {
            get {
                return ResourceManager.GetString("FacturaOrdenesDeDespacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetCanastilla].
        /// </summary>
        public static string GetCanastilla {
            get {
                return ResourceManager.GetString("GetCanastilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetClienteByGuid].
        /// </summary>
        public static string GetClienteByGuid {
            get {
                return ResourceManager.GetString("GetClienteByGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetEmpleadosByNombre].
        /// </summary>
        public static string GetEmpleadosByNombre {
            get {
                return ResourceManager.GetString("GetEmpleadosByNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetEstacion].
        /// </summary>
        public static string GetEstacion {
            get {
                return ResourceManager.GetString("GetEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetEstaciones].
        /// </summary>
        public static string GetEstaciones {
            get {
                return ResourceManager.GetString("GetEstaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetFacturaByEstado].
        /// </summary>
        public static string GetFacturaByEstado {
            get {
                return ResourceManager.GetString("GetFacturaByEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[getFacturaCanastilla].
        /// </summary>
        public static string getFacturaCanastilla {
            get {
                return ResourceManager.GetString("getFacturaCanastilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[getFacturaCanatillaDetalle].
        /// </summary>
        public static string getFacturaCanatillaDetalle {
            get {
                return ResourceManager.GetString("getFacturaCanatillaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[getFacturasCanastilla].
        /// </summary>
        public static string getFacturasCanastilla {
            get {
                return ResourceManager.GetString("getFacturasCanastilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetFacturasImprimir].
        /// </summary>
        public static string GetFacturasImprimir {
            get {
                return ResourceManager.GetString("GetFacturasImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetOrdenesDeDespacho].
        /// </summary>
        public static string GetOrdenesDeDespacho {
            get {
                return ResourceManager.GetString("GetOrdenesDeDespacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetOrdenesDeDespachoByFactura].
        /// </summary>
        public static string GetOrdenesDeDespachoByFactura {
            get {
                return ResourceManager.GetString("GetOrdenesDeDespachoByFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetOrdenesImprimir].
        /// </summary>
        public static string GetOrdenesImprimir {
            get {
                return ResourceManager.GetString("GetOrdenesImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetResolucionActiva].
        /// </summary>
        public static string GetResolucionActiva {
            get {
                return ResourceManager.GetString("GetResolucionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetTercero].
        /// </summary>
        public static string GetTercero {
            get {
                return ResourceManager.GetString("GetTercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetTerceros].
        /// </summary>
        public static string GetTerceros {
            get {
                return ResourceManager.GetString("GetTerceros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetTercerosActualizados].
        /// </summary>
        public static string GetTercerosActualizados {
            get {
                return ResourceManager.GetString("GetTercerosActualizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetTipoIdentificacionIdByTexto].
        /// </summary>
        public static string GetTipoIdentificacionIdByTexto {
            get {
                return ResourceManager.GetString("GetTipoIdentificacionIdByTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetTiposIdentificaciones].
        /// </summary>
        public static string GetTiposIdentificaciones {
            get {
                return ResourceManager.GetString("GetTiposIdentificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetUserByGuid].
        /// </summary>
        public static string GetUserByGuid {
            get {
                return ResourceManager.GetString("GetUserByGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetUserGuidByUserNPass].
        /// </summary>
        public static string GetUserGuidByUserNPass {
            get {
                return ResourceManager.GetString("GetUserGuidByUserNPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetUsuarios].
        /// </summary>
        public static string GetUsuarios {
            get {
                return ResourceManager.GetString("GetUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[HabilitarResolucion].
        /// </summary>
        public static string HabilitarResolucion {
            get {
                return ResourceManager.GetString("HabilitarResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[ListarClientes].
        /// </summary>
        public static string ListarClientes {
            get {
                return ResourceManager.GetString("ListarClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[GetFacturas].
        /// </summary>
        public static string ListarFactura {
            get {
                return ResourceManager.GetString("ListarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[ListarIslas].
        /// </summary>
        public static string ListarIsla {
            get {
                return ResourceManager.GetString("ListarIsla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[ListarSurtidor].
        /// </summary>
        public static string ListarSurtidor {
            get {
                return ResourceManager.GetString("ListarSurtidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModificarFactura {
            get {
                return ResourceManager.GetString("ModificarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AgregarOModificarIsla].
        /// </summary>
        public static string ModificarIsla {
            get {
                return ResourceManager.GetString("ModificarIsla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[ModificarSurtidor].
        /// </summary>
        public static string ModificarSurtidor {
            get {
                return ResourceManager.GetString("ModificarSurtidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].ObtenerFacturaPorGuid.
        /// </summary>
        public static string ObtenerFacturaPorGuid {
            get {
                return ResourceManager.GetString("ObtenerFacturaPorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObtenerFacturaPorIdVentaLocal.
        /// </summary>
        public static string ObtenerFacturaPorIdVentaLocal {
            get {
                return ResourceManager.GetString("ObtenerFacturaPorIdVentaLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[ObtenerIslaPorGuid].
        /// </summary>
        public static string ObtenerIslaPorGuid {
            get {
                return ResourceManager.GetString("ObtenerIslaPorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].ObtenerOrdenDespachoPorGuid.
        /// </summary>
        public static string ObtenerOrdenDespachoPorGuid {
            get {
                return ResourceManager.GetString("ObtenerOrdenDespachoPorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObtenerOrdenDespachoPorIdVentaLocal.
        /// </summary>
        public static string ObtenerOrdenDespachoPorIdVentaLocal {
            get {
                return ResourceManager.GetString("ObtenerOrdenDespachoPorIdVentaLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[ObtenerSurtidoresPorGuidIsla].
        /// </summary>
        public static string ObtenerSurtidoresPorGuidIsla {
            get {
                return ResourceManager.GetString("ObtenerSurtidoresPorGuidIsla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[ObtenerSurtidorPorGuid].
        /// </summary>
        public static string ObtenerSurtidorPorGuid {
            get {
                return ResourceManager.GetString("ObtenerSurtidorPorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].ObtenerTerceroPorIdentificacion.
        /// </summary>
        public static string ObtenerTerceroPorIdentificacion {
            get {
                return ResourceManager.GetString("ObtenerTerceroPorIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObtenerOrdenDespachoPorIdVentaLocal.
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[SaveOrUpdateCliente].
        /// </summary>
        public static string SaveOrUpdateCliente {
            get {
                return ResourceManager.GetString("SaveOrUpdateCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[SaveOrUpdateUser].
        /// </summary>
        public static string SaveOrUpdateUser {
            get {
                return ResourceManager.GetString("SaveOrUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[SetConsecutivoFacturaPendiente].
        /// </summary>
        public static string SetConsecutivoFacturaPendiente {
            get {
                return ResourceManager.GetString("SetConsecutivoFacturaPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[SetIdFacturacion].
        /// </summary>
        public static string SetIdFacturacion {
            get {
                return ResourceManager.GetString("SetIdFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].SetIdFacturaElectronicaFactura.
        /// </summary>
        public static string SetIdFacturaElectronicaFactura {
            get {
                return ResourceManager.GetString("SetIdFacturaElectronicaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[SetIdFacturaElectronicaOrdenesdeDespacho].
        /// </summary>
        public static string SetIdFacturaElectronicaOrdenesdeDespacho {
            get {
                return ResourceManager.GetString("SetIdFacturaElectronicaOrdenesdeDespacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[UpdateConsecutivoResolucion].
        /// </summary>
        public static string UpdateConsecutivoResolucion {
            get {
                return ResourceManager.GetString("UpdateConsecutivoResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[UpdateOrCreateCanastilla].
        /// </summary>
        public static string UpdateOrCreateCanastilla {
            get {
                return ResourceManager.GetString("UpdateOrCreateCanastilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[AgregarOActualizarEstacion].
        /// </summary>
        public static string UpdateOrCreateEstacion {
            get {
                return ResourceManager.GetString("UpdateOrCreateEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[UpdateOrCreateTerceros].
        /// </summary>
        public static string UpdateOrCreateTerceros {
            get {
                return ResourceManager.GetString("UpdateOrCreateTerceros", resourceCulture);
            }
        }
    }
}
